[package]
name = "dbuf-lsp"
edition = "2024"
version.workspace = true

[dependencies]
dbuf-core.workspace = true

tower-lsp.workspace = true
tokio.workspace = true
dashmap.workspace = true
pretty.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
